name: Build and Release

on:
  workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [darwin, windows, linux]
        arch: [amd64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
      run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ./bin/sber-scrape-linux-386 -v ./cmd/sber-scrape
    - name: Build for linux 386
      run: GOOS=linux GOARCH=386 go build -o ./bin/sber-scrape-linux-386 -v ./cmd/sber-scrape
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sber-scrape-linux-386
        path: ./bin/
    - name: Upload amd-64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sber-scrape-${{matrix.os}}-amd-64
        path: ./bin/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Binaries
      uses: actions/download-artifact@v3
      with:
        name: sber-scrape*

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./bin/sber-scrape* # Change this to match your binary file names
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
